config/routes.rb
Rails.application.routes.draw do
  root 'tweet#index'
  get 'likes/create'

   get "profiles/:id" => "profiles#show", as: :profile
   get "profiles" => "profiles#index"
  
   devise_for :users
   resources :tweets do 
     resource :like
   end 
   
   resources :relationships

  get "feed" => "profiles#feed"
end 
   

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, class_name: "User"
    
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :likes
 validates :message, presence: true, length: {maximum: 140, 
too_long: "A tweet is only 140 max. Everybody knows that!"}
end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :tweets 
  has_many :relationships
  has_many :friends, through: :relationships
  
  has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_relationships, :source => :user
  
  has_many :likes
  
  def likes?(tweet)
      tweet.likes.where(user_id: id).any?
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :bio, :location, :email, :password, :password_confirmation, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :bio, :location, :email, :password, :password_confirmation, :avatar])
	end
	
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet
  
  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create
    respond_to do |format|
      format.html { redirect_to request.referrer }
  end
  end

def destroy
  @tweet.likes.where(user_id: current_user.id).destroy_all
  respond_to do |format|
    format.html { redirect_to request.referrer }
  end 
end

private

def set_tweet
@tweet = Tweet.find(params[:tweet_id])
end

end 

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 
 def index
    @users = User.all
 end

  def show
    @user = User.find(params[:id])
  end
  
  def feed
    @tweet = Tweet.new
    @tweets = Tweet.where("user_id in (?) OR user_id = ?", current_user.friend_ids, current_user).order('created_at DESC')
end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
    @relationship = current_user.relationships.build(:friend_id => params[:friend_id])
  if @relationship.save
    flash[:notice] = "Followed successfully."
    redirect_to profile_path(current_user.id)
  else
    flash[:notice] = "Unable to follow."
    redirect_to root_path
  end
end

 def destroy
      @relationship.destroy
    respond_to do |format|
      format.html { redirect_to profile_path, notice: 'You are no longer friendsies.' }
    end
  end

private 

def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

    def update
    respond_to do |format|
        if @tweet.update(tweet_params)
          format.html { redirect_to @tweet, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }

      end
    end
  end

  def destroy
      @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
    end

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
ANSWER - BUTTON
<%= link_to "Sign Out", destroy_user_session_path, 
method: :delete, class: "btn btn-danger"%>

<%= link_to "Twitter Feed", feed_path, class:"btn btn-default" %>

</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/profiles/feed.html.erb
<div class="row">
  <div class= "col-xs-3 panel panel-default">
    <div class="panel-body">
      <div class="row">
        <h3><%= current_user.name %></h3>
        <h5><%= current_user.username %></h5>
      </div>
      <div class="row">
        <div class="col-xs-4">
          <span class="small text">TWEETS</span><br />
          <div data-toggle="modal" data-target=".tweet-modal">
            <%= current_user.tweets.count %>
          </div>
        </div>
        <div class="col-xs-4">
          <span class="small text">FOLLOWING</span><br />
          <div data-toggle="modal" data-target=".following-modal">
            <%= current_user.relationships.count %>
          </div>
        </div>
        <div class="col-xs-4">
          <span class="small text">FOLLOWERS</span><br />
          <div data-toggle="modal" data-target=".followers-modal">
            <%= current_user.inverse_relationships.count %>
          </div>
        </div>
      </div>
      <h5><p><%= current_user.bio %></p></h5>
      <h5><%= current_user.location %></h5>
      <h5>Joined in <%= current_user.created_at.strftime("%B %Y") %></h5>
    </div>
    </div>
    <div class= "col-xs-1"></div>

    <div class= "col-xs-7 panel panel-default">
      <div class="panel-body">
        <div class="well well-lg">
          <%= render 'tweets/form' %>
        </div>
        <% @tweets.each do |tweet|%>
        <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br />
        <br />
        <%= tweet.message %>
        <br />
        <br />
        <% if current_user.likes?(tweet) %>
          <%= link_to tweet_like_path(tweet), method: :delete do %>
            <i class="glyphicon glyphicon-heart like-button"> </i>
          <% end %>

          <% else %>
            <%= link_to tweet_like_path(tweet), method: :post do %>
            <i class="glyphicon glyphicon-heart"> </i>
          <% end %>
        <% end %>
        <br />
        <hr>
        <% end %>
      </div>

  </div>
</div>




<div class="modal fade tweet-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% current_user.tweets.each do |tweet| %>
        <%= tweet.message %><br />
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade followers-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% current_user.inverse_relationships.each do |relationship| %>
        <%= relationship.user_id %><br />
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade following-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% current_user.relationships.each do |relationship| %>
        <%= relationship.user_id %><br />
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<h1>All Users<h1/>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %> 
  <br />
<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class= "col-xs-4">
  <h3><%= @user.name %></h3>
  <h5><%= @user.username %></h5>
  <h5><p><%= @user.bio %></p></h5>
  <h5><%= @user.location %></h5>
  <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

  <%= @user.relationships.count %> Following
  <br />
  <% @user.relationships.each do |relationship| %>
    <%=link_to relationship.friend.name, profile_path(relationship.friend) %>
  <%end%>
  <br />
  <br />
  <%= pluralize(@user.inverse_relationships.count, "Follower") %>.
  <br />
  <% @user.inverse_friends.each do |friend| %>
    <%=link_to friend.name, profile_path(friend) %> <br />
  <%end%>
  </div>

  <div class= "col-xs-7">
    <div class="panel panel-default">
      <% @user.tweets.each do |tweet| %>
        <div class="panel-body">
        <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br />
        <br />
        <%= tweet.message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br />
<br />
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>
  <% else %>
    <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
  <% end %>
<% end %>

app/views/profiles/views.html.erb
<div class="row">
  <div class= "col-xs-3 panel panel-default">
    <div class="panel-body">
      <div class="row">
        <h3><%= current_user.name %></h3>
        <h5><%= current_user.username %></h5>
      </div>
      <div class="row">
        <div class="col-xs-4">
          <span class="small text">TWEETS</span><br />
          <div data-toggle="modal" data-target=".tweet-modal">
            <%= current_user.tweets.count %>
          </div>
        </div>
        <div class="col-xs-4">
          <span class="small text">FOLLOWING</span><br />
          <div data-toggle="modal" data-target=".following-modal">
            <%= current_user.relationships.count %>
          </div>
        </div>
        <div class="col-xs-4">
          <span class="small text">FOLLOWERS</span><br />
          <div data-toggle="modal" data-target=".followers-modal">
            <%= current_user.inverse_relationships.count %>
          </div>
        </div>
      </div>
      <h5><p><%= current_user.bio %></p></h5>
      <h5><%= current_user.location %></h5>
      <h5>Joined in <%= current_user.created_at.strftime("%B %Y") %></h5>
    </div>
    </div>
    <div class= "col-xs-1"></div>

    <div class= "col-xs-7 panel panel-default">
      <div class="panel-body">
        <div class="well well-lg">
          <%= render 'tweets/form' %>
        </div>
        <% @tweets.each do |tweet|%>
        <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br />
        <br />
        <%= tweet.message %>
        <br />
        <br />
        <% if current_user.likes?(tweet) %>
          <%= link_to tweet_like_path(tweet), method: :delete do %>
            <i class="glyphicon glyphicon-heart like-button"> </i>
          <% end %>

          <% else %>
            <%= link_to tweet_like_path(tweet), method: :post do %>
            <i class="glyphicon glyphicon-heart"> </i>
          <% end %>
        <% end %>
        <br />
        <hr>
        <% end %>
      </div>

  </div>
</div>




<div class="modal fade tweet-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% current_user.tweets.each do |tweet| %>
        <%= tweet.message %><br />
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade followers-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% current_user.inverse_relationships.each do |relationship| %>
        <%= relationship.user_id %><br />
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade following-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% current_user.relationships.each do |relationship| %>
        <%= relationship.user_id %><br />
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
<%= link_to "Unlike", tweet_like_path(@tweet), method: :delete %>
<% else %>
<%= link_to 'Like', tweet_like_path(@tweet), method: :post %>

<% end %>

<%= @tweet.likes.count %>

Liked by: 
<% @tweet.likes.each do |like| %>
<br />
<%= like.user.username %>
<br />
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  
  <div class="field cant-see-me">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
 <h1>Edit Tweet</h1>

<%= render  'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>This is your tweet index.</h1>

<table>
    <thead>
        <tr>
            <th>Message</th>
            <th>User</th>
            <th colspan="3"></th>
        </tr>
    </thead>
<tbody>
    <% @tweets.each do |tweet| %>
    <tr>
        <td><%=tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td> 
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: "are you sure?"} %></td>
    </tr>
    <% end %>
</tbody>
</table>
<br />
<%= link_to 'New Tweet', new_tweet_path %>
<%= link_to 'Delete Registration', destroy_user_session_path, method: :delete %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Message:</strong>
    <%= @tweet.message %>
</p>

<p>
      <strong>User:</strong>
    <%= @tweet.user.username %>
</p>

<%= render 'shared/likes' %>

<br />
<%= link_to 'Edit', edit_tweet_path(@tweet) %>
<%= link_to 'Back', tweets_path %>

<br />

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Log Out", destroy_user_session_path, method: :delete%>